name: CI for NestJS Todo Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Kodni yuklash
        uses: actions/checkout@v3

      - name: Docker Compose o‘rnatish
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Docker Compose bilan ishga tushirish
        run: docker-compose up -d

      - name: Server ishga tushishini kutish
        run: sleep 10
        
      - name: Tozalash
        run: docker-compose down
