name: CI for Todo Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Reponi yuklash
        uses: actions/checkout@v3

      - name: Docker Compose bilan ishga tushirish
        run: docker-compose up -d

      - name: Server ishga tushishini kutish
        run: sleep 10

      - name: 'Test: `/health` endpointni tekshirish'
        run: curl -f http://localhost:3000/health

      - name: Tozalash
        run: docker-compose down
